## YAML Template.
--- 
zkHosts: "zoo1.domain.com:2181,zoo2.domain.com:2181,zoo3.domain.com:2181"   
oddeyerulestable: oddeyerules
tsd.core.auto_create_metrics: false
tsd.storage.enable_compaction: false
tsd.storage.hbase.data_table: test_tsdb
tsd.storage.hbase.uid_table: test_tsdb-uid
   
