## YAML Template.
--- 
zkHosts: "nn1.netangels.net:2181,nn2.netangels.net:2181,rm1.netangels.net:2181"   
metatable: test_oddeye-meta
tsd.core.auto_create_metrics: false
tsd.storage.enable_compaction: false
tsd.storage.hbase.data_table: test_tsdb
tsd.storage.hbase.uid_table: test_tsdb-uid
   
kafka.zkHosts: "nn1.netangels.net:2181,nn2.netangels.net:2181,rm1.netangels.net:2181"      
kafka.topic: oddeyetsdb
kafka.groupId: oddeyetsdbcalculator_test